kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: beast
  namespace: api-link-gw
  labels:
    app: beast
    release: api-link-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: beast
      release: api-link-gw
  template:
    metadata:
      labels:
        app: beast
        release: api-link-gw
    spec:
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      containers:
        - resources: {}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          lifecycle:
            preStop:
              exec:
                command:
                  - sh
                  - '-c'
                  - 'kill -15 `ps aux | grep ''/usr/bin/java'' | awk ''{print $1}''`'
          name: beast
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          securityContext:
            privileged: true
          ports:
            - name: service
              containerPort: 8080
              protocol: TCP
            - name: actuator
              containerPort: 8000
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: beast
              mountPath: /data/beast
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: beast
            - secretRef:
                name: beast
          image: 3.39.117.244:5000/beast/api-link-gw/beast:api-link-gw-1.0.0
      hostAliases:
        - ip: 127.0.0.1
          hostnames:
            - beast.com
      volumes:
        - name: beast
          persistentVolumeClaim:
            claimName: beast
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: api-link-gw-nexus
  serviceName: beast
  podManagementPolicy: OrderedReady
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  revisionHistoryLimit: 10


