apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"name":"mongodb","namespace":"api-link-gw"},"spec":{"replicas":3,"selector":{"matchLabels":{"role":"mongodb"}},"serviceName":"beast-mongodb-svc","template":{"metadata":{"labels":{"environment":"dev","role":"mongodb"}},"spec":{"containers":[{"command":["mongod","--replSet","rs0","--smallfiles","--noprealloc","--bind_ip=0.0.0.0"],"image":"mongo","name":"mongo","ports":[{"containerPort":27017}]},{"env":[{"name":"MONGO_SIDECAR_POD_LABELS","value":"role=mongo,environment=dev"}],"image":"cvallance/mongo-k8s-sidecar","name":"mongo-sidecar"}],"terminationGracePeriodSeconds":10}}}}
  creationTimestamp: "2022-10-14T06:18:12Z"
  generation: 11
  name: mongodb
  namespace: api-link-gw
  resourceVersion: "11880457"
  uid: 3c9d64bb-3e7e-48c3-915a-3b93a1c0cf80
spec:
  podManagementPolicy: OrderedReady
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      role: mongodb
  serviceName: beast-mongodb-svc
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-10-14T06:38:50Z"
      creationTimestamp: null
      labels:
        environment: dev
        role: mongodb
    spec:
      containers:
      - command:
        - mongod
        - --replSet
        - replset
        - --bind_ip_all
        env:
        - name: MONGO_SIDECAR_POD_LABELS
          value: role=mongo,environment=dev
        image: mongo
        imagePullPolicy: Always
        name: mongo
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/
          name: beast-pvc
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 10
      volumes:
      - name: beast-pvc
        persistentVolumeClaim:
          claimName: beast
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 2
  collisionCount: 0
  currentReplicas: 2
  currentRevision: mongodb-5b4bcff9d5
  observedGeneration: 11
  readyReplicas: 2
  replicas: 3
  updateRevision: mongodb-c4746ff97
  updatedReplicas: 1
