apiVersion: v1
kind: ConfigMap
metadata:
  name: beast
  namespace: beast
data:
  PROFILE: dev
  JAVA_OPTS: '-Dserver.port=8080 -Ddata.system[0].sysId=MNGT -Ddata.system[0].edpt.prot=HTTP -Ddata.system[0].edpt.atrib.url[0]=http://portal-b:8080 -Dspring.data.mongodb.uri=mongodb://mongodb-0.mongodb:27017,mongodb-1.mongodb:27017,mongodb-2.mongodb:27017 -Dspring.data.mongodb.database=APIGW -Dspring.data.mongodb.username=act_user -Dspring.data.mongodb.password=sksmsahffk1! -Dspring.data.primary.mongodb.uri=mongodb://mongodb-0.mongodb:27017,mongodb-1.mongodb:27017,mongodb-2.mongodb:27017/?readPreference=nearest -Dspring.data.primary.mongodb.database=APIGW -Dspring.data.primary.mongodb.username=act_user -Dspring.data.primary.mongodb.password=sksmsahffk1! -Dspring.data.secondary.mongodb.uri=mongodb://mongodb-0.mongodb:27017,mongodb-1.mongodb:27017,mongodb-2.mongodb:27017/?readPreference=nearest -Dspring.data.secondary.mongodb.database=TBAPIGW -Dspring.data.secondary.mongodb.username=act_user -Dspring.data.secondary.mongodb.password=sksmsahffk1!'
  nginx.conf: |-
    user  nginx;
    worker_processes  auto;
    
    error_log  /var/log/nginx/error.log notice;
    pid        /var/run/nginx.pid;
    
    
    events {
        worker_connections  1024;
    }
    
    
    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;
    
        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for"';
    
        access_log  /var/log/nginx/access.log  main;
    
        sendfile        on;
    
        keepalive_timeout  65;
    
        server {
                listen       80;
                listen  [::]:80;
                server_name  localhost;
        
                access_log  /var/log/nginx/host.access.log  main;
        
                client_max_body_size 15M;
                location / {
                        root   /usr/share/nginx/html/dist;
                        index  index.html index.htm;
                        try_files $uri $uri/ /index.html;
                }
        
                error_page   500 502 503 504  /50x.html;
        
                location = /50x.html {
                        root   /usr/share/nginx/html;
                }
        
                location ~ /mngt/ {
                        if ($request_method = 'OPTIONS') {
                                add_header 'Access-Control-Allow-Origin' $http_origin;
                                add_header 'Access-Control-Allow-Methods' $http_access_control_request_method;
                                add_header 'Access-Control-Allow-Headers' $http_access_control_request_headers;
                                add_header 'Access-Control-Allow-Credentials' 'true';
                                return 204;
                        }
                        proxy_pass http://beast:8080;
                }
        
                location /stomp/ws {
                        proxy_pass http://portal-b:8080;
                        proxy_http_version 1.1;
                        proxy_set_header Upgrade $http_upgrade;
                        proxy_set_header Connection "Upgrade";
                }
        
                add_header X-Frame-Options DENY;
        }
    }  
