kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: api-link-gw-efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c40a8bdebbb6ef3e
  directoryPerms: "700"
  gidRangeStart: "1000" # optional
  gidRangeEnd: "2000" # optional
  basePath: "/dynamic_provisioning" # optional
