apiVersion: v1
kind: Service
metadata:
  name: test-front
spec:
  type: NodePort
  selector:
    app: test-front
    tier: front
  ports:
    - name: http
      protocol: TCP
      port: 27018
      nodePort: 27017
